# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies without running pre/post install scripts
RUN npm install --ignore-scripts

# Copy app source
COPY . .

# Build the project
RUN npm run build

# Expose any necessary ports if needed (for example 3000 if the server listens on a port)
# EXPOSE 3000

# Use the node binary to run the built server
CMD ["node", "build/index.js"]
